config/routes.rb
Rails.application.routes.draw do
  root    'static#home'

  post    'events/create' => 'events#create', as: :create_event
  get     'events'=> 'events#index', as: :events
  post    'events/join' => 'events#join', as: :join_event
  get     'events/:event_code'  => 'events#show', as: :event
  get     'events/:event_code/display'  => 'events#display', as: :display_event
  post    'events/:event_code/messages' => 'messages#create', as: :event_messages
  get     'events/:event_code/messages' => 'messages#index'
  get     'events/:event_code/messages/:id' => 'messages#show', as: :event_message

  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :messages
  validates :name, :code, :presence => true
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_save :downcase_email

  belongs_to :event
  validates :event, presence: true
  validates :body, :presence => true
 
  private
  def downcase_email
      self.email = email.downcase if email.present?
  end
end

app/models/user.rb
# require_dependency 'app/validators/email_validator.rb'
# https://developer.salesforce.com/forums/?id=906F00000008tJpIAI require 'EmailValidator' 

class EmailValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end

end

class User < ActiveRecord::Base
  before_save :downcase_email

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 200 }
  validates :email, email: true
  validates :email, uniqueness: { case_sensitive: false }

  has_secure_password

  private 

  def downcase_email
      self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @message = Message.new
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :logged_in_user, only: [:create, :index]

  def join
    event_code = params[:event][:code]
    @event = Event.find_by(code: event_code)
    if (@event)
      redirect_to event_path(@event.code)
    else
      flash[:alert] = "No event was found with code #{event_code}"
      render 'static/home'
    end
  end

  def create
    
    @event = Event.new(event_params)

    if(@event.save)
        redirect_to events_path
    else
      @events = Event.all.order(:name)
      render :index
    end
  end

  def index
    @events = Event.all.order(:name)
    @event = Event.new
  end

  def show
    @event = Event.find_by(code: params[:event_code])
    if (@event)
      @message = @event.messages.new
    else
      flash[:alert] = "No event was found with code #{event_code}"
      render 'static/home'
    end
  end

  def display
    @event = Event.find_by(code: params[:event_code])
  end

  private

  def event_params
      params.require(:event).permit(:name, :code, :image_url)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @event = Event.find_by(code: params[:event_code])
    @message = @event.messages.new(message_params)
    
    respond_to do |format|  
      if @event.save  
          format.js   { }
          format.json { render :show, status: :created, location: event_message_url(@event, @message) }
      else 
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @event = Event.find_by(code: params[:event_code])
    @message = @event.messages.find(params[:id])

    respond_to do |format|  
          format.html   { }
          format.json { render :show, status: :created, location: event_message_url(@event, @message) }
    end
  end
    
  def index
    
    @event = Event.find_by(code: params[:event_code])

    if (params.has_key?(:after))
      time_of_latest_message = Time.at(params[:after].to_i + 1)
      @messages = @event.messages.order(created_at: :desc).where("created_at > ?", time_of_latest_message)
    else
      @messages = @event.messages.order(created_at: :desc)
    end
    respond_to do |format|
      format.js
      format.json 
	  end
  end

  private 
  
  def message_params
      params.require(:message).permit(:body, :email, :username)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        log_in(user)
        redirect_to events_path
    else
        flash.now[:alert] = "Invalid email or password" 
        render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(message)
    default_amage_url = CGI.escape("https://www.usabmx.com/images/bmx/site/default_profile_avatar_48.png?1440099072")
    
    identifier = ""
    identifier = message.username if message.username.present?
    identifier = message.email if message.email.present?
    
    gravatar_id = Digest::MD5.hexdigest(identifier.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48&d=identicon"
  end

  def markdown(content)
    options = [hard_wrap: true, filter_html: true, autolink: true, no_intraemphasis: true, space_after_headers: true, fenced_code_blocks: true, gh_blockcode: true, highlight: true]
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, *options)
    @markdown.render(h content).html_safe
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/events/display.html.erb
<% content_for :event_header, render(partial: "shared/event_header", locals: {event: @event})  %>
<div id="commentary" data-event="<%= @event.code %>" class="lead">

app/views/events/index.html.erb
<%= link_to "Admin Logout", logout_path, method: "delete"  %>

<h3>Create Event</h3>
<div class="row">
  <%= form_for(@event, url: create_event_path, html: {class: "form col-xs-5"}) do |f| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <p><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</p>
     
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :code %>
      <%= f.text_field :code, class: 'form-control' %>
    </div>
      <div class="form-group">
      <%= f.label :image_url %>
      <%= f.text_field :image_url, class: 'form-control' %>
    </div>
    <%= f.submit nil, class: "btn btn-primary" %>
  <% end %>
</div>
<div class="col-xs-12" style="height:50px;"></div>

<h3>All Events</h3>

<% @events.each do | event | %>

  <div class="row">
    <div class="col-xs-6"><%= link_to event.name, event_path(event.code) %></div>
  </div>

<% end %>

app/views/events/show.html.erb
<% content_for :event_header, render(partial: "shared/event_header", locals: {event: @event})  %>

<div class="row">
<%= form_for([@event, @message], url: event_messages_path(@event.code), remote: true, html: {class: "form col-md-6"}) do |f| %>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.text_area :body, rows: 3, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.submit "Comment", class: "btn btn-default pull-right" %>
    </div>
  <% end %>
</div>

<br />
<div id="commentary" data-event="<%= @event.code %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if logged_in? && false %>
      <%= link_to "Log out", logout_path, method: "delete"  %>
      <%= link_to "Admin Login", login_path %> | 
    <% else %>
        
    <% end %>

    <% if (! (current_page?(root_path))) %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
          <div class="navbar-header">
            <% if content_for?(:event_header) %>
              <%= content_for(:event_header) %>
            <% else %>
              <a class="navbar-brand" href="#">Skinder</a>
            <% end %>
          </div>
      </div>
    </nav>
    <% end %>
  
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="comment row" data-time="<%= message.created_at.to_i %>">
  <div class="col-xs-1 vcenter"  ><%= image_tag avatar_url(message) %></div><!--
    -->
  <div class="col-xs-9 vcenter"><%= markdown(h(message.body)) %></div>
</div>
<hr />
    

app/views/messages/create.js.erb
$('input[name="commit"]').attr('disabled',true);
$("#message_body").val('');
$("#message_body").focus();
// updateMessages();
window.globCounter = 0;

app/views/messages/index.js.erb
var message = $("<%= j render @messages %>");
message.find(".speech").on('click', function(e){

 // alert("hi"); 

  var $link = $(this);
  var message = $link.attr("data-speech");
  console.log(message);
  var msg = new SpeechSynthesisUtterance(message);
  window.speechSynthesis.speak(msg);
  return false;

});
message.hide();
$("#commentary").prepend(message);
message.slideDown();

app/views/shared/_event_header.html.erb
<% if event.image_url.present? %>
  <!-- <a href="#" class="pull-left"><img src="/path/to/image.png"></a> -->
  <%= link_to(image_tag(event.image_url, height: "48"), event_path(event.code), class: "pull-left") %>
<% end %>
 
<%= link_to("#{event.name}", event_path(event.code), id: "event-header", class: "navbar-brand") %>